### PR TITLE
Replace `LazyArrays` with `BlockArrays` backend

### LINKED ISSUE #11: Performance difference between LazyWAVFile and DistributedWAVFile
By running the following code,
```Julia
using BenchmarkTools, LazyWAVFiles, WAV

path = mktempdir()
y = sin.((0:99999999)/48000*2pi*440);
wavwrite(y, joinpath(path, "test1.wav"), Fs=48000)

dfile = DistributedWAVFile(path)

indices1 = 1:96000
@btime dfile[indices1]
indices2 = 96000:96000*2
@btime dfile[indices2]
indices3 = 96000*10:96000*11
@btime dfile[indices3]

filepath = joinpath(path, "test1.wav")
lfile = LazyWAVFile(filepath)

indices1 = 1:96000
@btime lfile[indices1]
indices2 = 96000:96000*2
@btime lfile[indices2]
indices3 = 96000*10:96000*11
@btime lfile[indices3]
```
the output is
```Julia
2.218 s (5568005 allocations: 306.52 MiB)
2.599 s (5568063 allocations: 306.52 MiB)
2.558 s (5568063 allocations: 306.52 MiB)
181.882 μs (62 allocations: 1.10 MiB)
176.851 μs (62 allocations: 1.10 MiB)
181.919 μs (62 allocations: 1.10 MiB)
```

 The version of Julia in use is
```Julia
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4
```

### PR DESCRIPTION
**Pull request by ymtoo**
Fixes #11

### CODE REVIEW

**Comment by baggepinnen** [comment]
Thanks :D It looks like tests are failing on julia v1.0. I don't mind ditching compatibility with Julia v1.0 to ease the maintenance burden

**Comment by ymtoo** [comment]
OK, the test works fine on Julia 1.4

**Comment by baggepinnen** [comment]
I added some tests for type inference, it seems the new indexing approach is not type stable 
https://github.com/baggepinnen/LazyWAVFiles.jl/pull/13/checks?check_run_id=676972073#step:4:95
You can update your branch by `git pull` to get my changes, I pushed them to your branch.

I also added some benchmarks to make sure future changes to the array backend that cause regressions are caught early

**Comment by ymtoo** [comment]
The current fast indexing only works on 1D `DistributedWAVFile` (N=1). For N>1, `DistributedWAVFile` indexing falls back to the `BlockArrays` implementation which could be slower due to scalar array indexing.

**Comment by baggepinnen** [comment]
Awesome, thanks :)
We can always add customized methods for 2D distributed files if the need arises

**Pull request merged**
